Repository alexa/ask-cli, pull requests merged in 2022-08, with the labels that each got.

#410 feat: add skill events property to ask-resources.json
  docs/concepts/Alexa-Skill-Project-Definition.md
  lib/controllers/skill-infrastructure-controller/index.js
  lib/model/manifest.js
  lib/model/resources-config/ask-resources.js
  lib/model/resources-config/index.js
  test/unit/controller/skill-infrastructure-controller-test.js
  test/unit/fixture/model/regular-proj/ask-resources.json
Labels: Feature Request

#392 feat: add lambda deployer additional user config function parameters
  docs/concepts/Deploy-Command.md
  lib/builtins/deploy-delegates/lambda-deployer/helper.js
  lib/clients/aws-client/iam-client.js
  lib/clients/aws-client/lambda-client.js
  lib/utils/constants.js
  test/unit/builtins/lambda-deployer/helper-test.js
  test/unit/clients/aws-client/iam-client-test.js
  test/unit/clients/aws-client/lambda-client-test.js
Labels: Feature Request

#438 chore: updated hosted skill documentation link
  lib/commands/new/index.js
  lib/utils/constants.js
  test/unit/commands/new/index-test.js
Labels: Easy To Review PR

#391 fix: limit skill infrastructure deployment to one task per aws region
  lib/builtins/deploy-delegates/cfn-deployer/index.js
  lib/builtins/deploy-delegates/lambda-deployer/index.js
  lib/controllers/skill-infrastructure-controller/index.js
  lib/view/multi-tasks-view.js
  test/unit/builtins/cfn-deployer/index-test.js
  test/unit/builtins/lambda-deployer/index-test.js
  test/unit/controller/skill-infrastructure-controller-test.js
  test/unit/view/multi-tasks-view-test.js
Labels: Bug
